# Generated by Django 2.1 on 2018-08-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Num')),
            ],
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='exportfile',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='alech.ExportRequest'),
        ),
    ]
